In [1]:
import scanpy as sc
import squidpy as sq
import pandas as pd
import numpy as np

# Load files on Evan's Laptop
# expr_orig = pd.read_csv(r"C:\Users\evanj\OneDrive\Documents\expression.csv", index_col=0)
# expr=expr_orig.transpose()
# metadata = pd.read_csv(r"C:\Users\evanj\OneDrive\Documents\metadata.csv", index_col=0)
# umap = pd.read_csv(r"C:\Users\evanj\OneDrive\Documents\umap.csv", index_col=0)

#Load files on Lab computer
expr_orig = pd.read_csv(r"C:\Users\ejohns\Documents\Shapiro Data Files\expression.csv", index_col=0)
expr=expr_orig.transpose()
metadata = pd.read_csv(r"C:\Users\ejohns\Documents\Shapiro Data Files\metadata.csv", index_col=0)
umap = pd.read_csv(r"C:\Users\ejohns\Documents\Shapiro Data Files\umap.csv", index_col=0)

# Create AnnData object
adata = sc.AnnData(X=expr.values)

# Assign metadata
adata.obs = metadata
adata.var_names = expr.columns
adata.obs_names = expr.index

# Add spatial coordinates and UMAP to .obsm
# adata.obsm["spatial"] = metadata[['x_FOV_px', 'y_FOV_px']].values  # adjust if needed
adata.obsm["spatial"] = metadata[['x_FOV_px']].assign(y_FOV_px = -metadata['y_FOV_px']).values
adata.obsm["X_umap"] = umap.values

C:\Users\ejohns\AppData\Local\anaconda3\Lib\site-packages\paramiko\pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
C:\Users\ejohns\AppData\Local\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
  "class": algorithms.Blowfish,
C:\Users\ejohns\AppData\Local\anaconda3\Lib\site-packages\paramiko\transport.py:243: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
C:\Users\ejohns\AppData\Local\anaconda3\Lib\site-packages\anndata\utils.py:434: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)

In [2]:
import my_functions

res = my_functions.type_neighboors(adata, 1, 1) 
x, y = res["num_neigh"], res["type_neigh"]
display(x)
display(y)

[NbConvertApp] Converting notebook my_functions.ipynb to python
[NbConvertApp] Writing 8664 bytes to my_functions.py

            TMA  Sample  Number of Cells
Cell Id
c_1_1_46      1       1             14.0
c_1_1_171     1       1             17.0
c_1_1_354     1       1             19.0
c_1_1_384     1       1             19.0
c_1_1_410     1       1             17.0
c_1_1_439     1       1             17.0
c_1_1_534     1       1             19.0
c_1_1_556     1       1             16.0
c_1_1_580     1       1             18.0
c_1_1_597     1       1             19.0
c_1_1_650     1       1             20.0
c_1_1_675     1       1             20.0
c_1_1_681     1       1             17.0
c_1_1_702     1       1             17.0
c_1_1_713     1       1             17.0
c_1_1_790     1       1             21.0
c_1_1_868     1       1             21.0
c_1_1_909     1       1             19.0
c_1_1_942     1       1             20.0
c_1_1_967     1       1             18.0
c_1_1_1716    1       1              8.0
c_1_1_1749    1       1             12.0
c_1_1_1845    1       1             18.0
c_1_1_1880    1       1             17.0
c_1_1_1908    1       1             19.0
c_1_1_1915    1       1             16.0
c_1_1_2008    1       1             19.0
c_1_1_2050    1       1             14.0
c_1_1_2087    1       1             16.0
c_1_1_2109    1       1             19.0
c_1_1_2193    1       1             12.0
c_1_1_2206    1       1             17.0
c_1_1_2248    1       1             20.0
c_1_1_2284    1       1             18.0
c_1_1_2286    1       1             24.0
c_1_1_2395    1       1             16.0
c_1_1_2402    1       1             20.0
c_1_1_2490    1       1             16.0
c_1_1_2587    1       1             14.0
c_1_1_2644    1       1             13.0
c_1_1_2707    1       1             15.0
c_1_1_2785    1       1             15.0
c_1_1_3001    1       1             18.0
c_1_1_3080    1       1             16.0
c_1_1_3229    1       1             16.0
c_1_1_3529    1       1             17.0
c_1_1_4208    1       1             18.0
c_1_1_4237    1       1             20.0
c_1_1_4375    1       1             15.0
c_1_1_4648    1       1             20.0
c_1_1_4708    1       1             24.0
c_1_1_4965    1       1             17.0
c_1_1_5937    1       1             16.0
c_1_1_6291    1       1             21.0
c_1_1_6363    1       1             21.0

,Cell Id,TMA_num,punch_num,Number of Neighbors,Neighbor Cell Types
0,c_1_1_46,1,1,14.0,"{'Unknown': 4, 'Endothelial': 3, 'CD4+ T cell'..."
1,c_1_1_171,1,1,17.0,"{'Endothelial': 7, 'Unknown': 5, 'B cell': 3, ..."
2,c_1_1_354,1,1,19.0,"{'Endothelial': 9, 'Unknown': 5, 'B cell': 4, ..."
3,c_1_1_384,1,1,19.0,"{'Endothelial': 10, 'Unknown': 6, 'Macrophage/..."
4,c_1_1_410,1,1,17.0,"{'Endothelial': 7, 'Unknown': 5, 'B cell': 3, ..."
5,c_1_1_439,1,1,17.0,"{'Endothelial': 8, 'Unknown': 5, 'Macrophage/m..."
6,c_1_1_534,1,1,19.0,"{'Endothelial': 9, 'Unknown': 3, 'CD4+ T cell'..."
7,c_1_1_556,1,1,16.0,"{'Endothelial': 8, 'Fibroblast': 3, 'CD4+ T ce..."
8,c_1_1_580,1,1,18.0,"{'Endothelial': 9, 'Fibroblast': 4, 'CD4+ T ce..."
9,c_1_1_597,1,1,19.0,"{'Endothelial': 10, 'Fibroblast': 6, 'Unknown'..."
10,c_1_1_650,1,1,20.0,"{'Endothelial': 8, 'Fibroblast': 6, 'Macrophag..."
11,c_1_1_675,1,1,20.0,"{'Endothelial': 10, 'B cell': 5, 'Fibroblast':..."
12,c_1_1_681,1,1,17.0,"{'Endothelial': 5, 'B cell': 5, 'Fibroblast': ..."
13,c_1_1_702,1,1,17.0,"{'Endothelial': 6, 'B cell': 5, 'Macrophage/mo..."
14,c_1_1_713,1,1,17.0,"{'Endothelial': 7, 'B cell': 4, 'Macrophage/mo..."
15,c_1_1_790,1,1,21.0,"{'Endothelial': 10, 'Unknown': 4, 'Other immun..."
16,c_1_1_868,1,1,21.0,"{'Endothelial': 11, 'B cell': 5, 'Other immune..."
17,c_1_1_909,1,1,19.0,"{'B cell': 7, 'Endothelial': 7, 'Other immune'..."
18,c_1_1_942,1,1,20.0,"{'Endothelial': 9, 'B cell': 4, 'Other immune'..."
19,c_1_1_967,1,1,18.0,"{'Endothelial': 6, 'Vascular smooth muscle': 4..."
20,c_1_1_1716,1,1,8.0,"{'Endothelial': 3, 'Unknown': 3, 'Macrophage/m..."
21,c_1_1_1749,1,1,12.0,"{'Endothelial': 6, 'Unknown': 4, 'Macrophage/m..."
22,c_1_1_1845,1,1,18.0,"{'Endothelial': 9, 'Unknown': 6, 'Macrophage/m..."
23,c_1_1_1880,1,1,17.0,"{'Endothelial': 7, 'Unknown': 5, 'CD8+ T cell'..."
24,c_1_1_1908,1,1,19.0,"{'Endothelial': 7, 'Unknown': 5, 'CD4+ T cell'..."
25,c_1_1_1915,1,1,16.0,"{'Endothelial': 5, 'Unknown': 4, 'CD4+ T cell'..."
26,c_1_1_2008,1,1,19.0,"{'Endothelial': 7, 'Unknown': 4, 'CD8+ T cell'..."
27,c_1_1_2050,1,1,14.0,"{'Endothelial': 3, 'Unknown': 3, 'CD8+ T cell'..."
28,c_1_1_2087,1,1,16.0,"{'Endothelial': 5, 'Unknown': 3, 'CD8+ T cell'..."
29,c_1_1_2109,1,1,19.0,"{'Endothelial': 6, 'CD8+ T cell': 4, 'Unknown'..."
30,c_1_1_2193,1,1,12.0,"{'Unknown': 4, 'Endothelial': 3, 'Macrophage/m..."
31,c_1_1_2206,1,1,17.0,"{'Endothelial': 8, 'Unknown': 4, 'B cell': 2, ..."
32,c_1_1_2248,1,1,20.0,"{'Endothelial': 8, 'B cell': 4, 'Macrophage/mo..."
33,c_1_1_2284,1,1,18.0,"{'Endothelial': 5, 'B cell': 5, 'Unknown': 4, ..."
34,c_1_1_2286,1,1,24.0,"{'Endothelial': 9, 'Unknown': 5, 'B cell': 4, ..."
35,c_1_1_2395,1,1,16.0,"{'B cell': 5, 'Unknown': 4, 'Macrophage/monocy..."
36,c_1_1_2402,1,1,20.0,"{'Unknown': 5, 'Endothelial': 5, 'B cell': 4, ..."
37,c_1_1_2490,1,1,16.0,"{'Unknown': 4, 'Endothelial': 4, 'B cell': 3, ..."
38,c_1_1_2587,1,1,14.0,"{'Endothelial': 7, 'Unknown': 5, 'Other immune..."
39,c_1_1_2644,1,1,13.0,"{'Endothelial': 6, 'Unknown': 5, 'Macrophage/m..."
40,c_1_1_2707,1,1,15.0,"{'Endothelial': 9, 'Unknown': 4, 'Macrophage/m..."
41,c_1_1_2785,1,1,15.0,"{'Endothelial': 8, 'Unknown': 3, 'B cell': 2, ..."
42,c_1_1_3001,1,1,18.0,"{'Endothelial': 10, 'B cell': 4, 'Unknown': 3,..."
43,c_1_1_3080,1,1,16.0,"{'Endothelial': 5, 'B cell': 5, 'Unknown': 4, ..."
44,c_1_1_3229,1,1,16.0,"{'Endothelial': 7, 'Unknown': 6, 'Macrophage/m..."
45,c_1_1_3529,1,1,17.0,"{'Endothelial': 8, 'Unknown': 3, 'B cell': 3, ..."
46,c_1_1_4208,1,1,18.0,"{'Endothelial': 7, 'B cell': 5, 'Macrophage/mo..."
47,c_1_1_4237,1,1,20.0,"{'Endothelial': 10, 'B cell': 5, 'Macrophage/m..."
48,c_1_1_4375,1,1,15.0,"{'Endothelial': 6, 'B cell': 4, 'Macrophage/mo..."
49,c_1_1_4648,1,1,20.0,"{'Endothelial': 9, 'Unknown': 4, 'Other immune..."
50,c_1_1_4708,1,1,24.0,"{'Endothelial': 13, 'Unknown': 3, 'Other immun..."
51,c_1_1_4965,1,1,17.0,"{'Endothelial': 8, 'B cell': 5, 'Other immune'..."
52,c_1_1_5937,1,1,16.0,"{'Endothelial': 11, 'Vascular smooth muscle': ..."
53,c_1_1_6291,1,1,21.0,"{'Endothelial': 12, 'CD4+ T cell': 5, 'Unknown..."
54,c_1_1_6363,1,1,21.0,"{'Endothelial': 11, 'CD4+ T cell': 6, 'Unknown..."